language: java
jdk:
  - openjdk8

after_success:
  - |
    if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then \
       nvm install lts/* && \
       npm i @semantic-release/changelog @semantic-release/exec && \
       npx semantic-release@17; \
    fi

branches:
  only:
    - master
